steps:
  # 1. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/web-stranica-wwwleronebarcom/wwwleronebarcom', '.']

  # 2. Push Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/web-stranica-wwwleronebarcom/wwwleronebarcom']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'wwwleronebarcom',
        '--image', 'gcr.io/web-stranica-wwwleronebarcom/wwwleronebarcom',
        '--platform', 'managed',
        '--region', 'europe-west1',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/web-stranica-wwwleronebarcom/wwwleronebarcom'

options:
  logging: CLOUD_LOGGING_ONLY